name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change directory to TesteAutomatizado
        run: cd TesteAutomatizado

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          MANAGEMENT_TOKEN: ${{ secrets.MANAGEMENT_TOKEN }}
          INVALID_TOKEN: ${{ secrets.INVALID_TOKEN }}
        run: npx playwright test
